import "server-only";

import type { User } from "@supabase/supabase-js";
import type { Plan } from "@/lib/constants";
import { DEMO_EMAIL } from "@/lib/demo-session";
import { monthStart } from "@/lib/format";
import type { WorkspaceContext } from "@/lib/data/workspace";
import type {
  Account,
  ActivityEvent,
  Approval,
  BillPayment,
  Budget,
  CoupleWorkspace,
  Debt,
  DocumentRow,
  Expense,
  GoalWithContributions,
  IncomeSource,
  InvestmentWithHoldings,
  MoneyCheckin,
  Profile,
  ResearchItem,
  Task,
  WorkspaceMember,
  WorkspaceMemberWithProfile,
} from "@/lib/types/database";

const ALEX_ID = "11111111-1111-1111-1111-111111111111";
const JAMIE_ID = "22222222-2222-2222-2222-222222222222";
const WORKSPACE_ID = "33333333-3333-3333-3333-333333333333";

function dateOnly(date: Date) {
  return date.toISOString().slice(0, 10);
}

function daysAgo(days: number) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return dateOnly(date);
}

function isoDaysAgo(days: number) {
  return `${daysAgo(days)}T12:00:00.000Z`;
}

function currentMonthDate(day: number) {
  const now = new Date();
  return dateOnly(new Date(now.getFullYear(), now.getMonth(), day));
}

function previousMonthDate(day: number) {
  const now = new Date();
  return dateOnly(new Date(now.getFullYear(), now.getMonth() - 1, day));
}

const alex: Profile = {
  id: ALEX_ID,
  email: DEMO_EMAIL,
  full_name: "Alex Rivera",
  avatar_url: null,
  currency: "USD",
  onboarding_step: 10,
  onboarding_complete: true,
  risk_comfort: 4,
  money_style_pref: "hybrid",
  share_personal_net_worth: true,
  financial_stress_notes: null,
  priorities: ["Emergency fund", "Home down payment", "Lower debt"],
  is_platform_admin: true,
  created_at: isoDaysAgo(90),
  updated_at: isoDaysAgo(1),
};

const jamie: Profile = {
  id: JAMIE_ID,
  email: "jamie@demo.togetherwealth.app",
  full_name: "Jamie Chen",
  avatar_url: null,
  currency: "USD",
  onboarding_step: 10,
  onboarding_complete: true,
  risk_comfort: 3,
  money_style_pref: "hybrid",
  share_personal_net_worth: true,
  financial_stress_notes: null,
  priorities: ["Travel", "Retirement", "Monthly check-ins"],
  is_platform_admin: false,
  created_at: isoDaysAgo(90),
  updated_at: isoDaysAgo(1),
};

const workspace: CoupleWorkspace = {
  id: WORKSPACE_ID,
  name: "Alex & Jamie",
  money_style: "hybrid",
  default_split_method: "income_based",
  default_split_config: null,
  currency: "USD",
  created_by: ALEX_ID,
  created_at: isoDaysAgo(90),
  updated_at: isoDaysAgo(1),
};

const membership: WorkspaceMember = {
  id: "44444444-4444-4444-4444-444444444444",
  workspace_id: WORKSPACE_ID,
  user_id: ALEX_ID,
  role: "owner",
  joined_at: isoDaysAgo(90),
};

const partnerMembership: WorkspaceMember = {
  id: "55555555-5555-5555-5555-555555555555",
  workspace_id: WORKSPACE_ID,
  user_id: JAMIE_ID,
  role: "partner",
  joined_at: isoDaysAgo(88),
};

export type DemoRows = {
  accounts: Account[];
  incomeSources: IncomeSource[];
  expenses: Expense[];
  billPayments: BillPayment[];
  budgets: Budget[];
  goals: GoalWithContributions[];
  investments: InvestmentWithHoldings[];
  debts: Debt[];
  researchItems: ResearchItem[];
  checkins: MoneyCheckin[];
  documents: DocumentRow[];
  tasks: Task[];
  events: ActivityEvent[];
  approvals: Approval[];
};

export function getDemoWorkspaceContext(): WorkspaceContext {
  const members: WorkspaceMemberWithProfile[] = [
    { ...membership, profile: alex },
    { ...partnerMembership, profile: jamie },
  ];

  return {
    user: {
      id: ALEX_ID,
      email: alex.email,
      aud: "authenticated",
      role: "authenticated",
      app_metadata: {},
      user_metadata: { full_name: alex.full_name },
      created_at: alex.created_at,
      updated_at: alex.updated_at,
    } as User,
    profile: alex,
    workspace,
    membership,
    members,
    partner: jamie,
    plan: "plus" as Plan,
    subscription: {
      id: "66666666-6666-6666-6666-666666666666",
      workspace_id: WORKSPACE_ID,
      plan: "plus",
      status: "active",
      stripe_customer_id: null,
      stripe_subscription_id: null,
      current_period_end: null,
      cancel_at_period_end: false,
      created_at: isoDaysAgo(90),
      updated_at: isoDaysAgo(1),
    },
    isDemo: true,
  };
}

export function getDemoRows(): DemoRows {
  const currentMonth = monthStart(new Date());
  const nextQuarter = new Date();
  nextQuarter.setMonth(nextQuarter.getMonth() + 4);
  const nextYear = new Date();
  nextYear.setFullYear(nextYear.getFullYear() + 1);

  return {
    accounts: [
      {
        id: "acct-checking",
        workspace_id: WORKSPACE_ID,
        owner_id: ALEX_ID,
        name: "Everyday checking",
        type: "checking",
        institution: "Demo Bank",
        balance: 6420,
        currency: "USD",
        visibility: "shared",
        is_joint: true,
        notes: null,
        created_at: isoDaysAgo(80),
        updated_at: isoDaysAgo(1),
      },
      {
        id: "acct-emergency",
        workspace_id: WORKSPACE_ID,
        owner_id: JAMIE_ID,
        name: "Emergency savings",
        type: "savings",
        institution: "Demo Bank",
        balance: 14850,
        currency: "USD",
        visibility: "household",
        is_joint: true,
        notes: null,
        created_at: isoDaysAgo(80),
        updated_at: isoDaysAgo(1),
      },
      {
        id: "acct-private",
        workspace_id: WORKSPACE_ID,
        owner_id: ALEX_ID,
        name: "Personal buffer",
        type: "savings",
        institution: "Credit Union",
        balance: 3200,
        currency: "USD",
        visibility: "private",
        is_joint: false,
        notes: null,
        created_at: isoDaysAgo(70),
        updated_at: isoDaysAgo(3),
      },
    ],
    incomeSources: [
      {
        id: "income-alex",
        workspace_id: WORKSPACE_ID,
        owner_id: ALEX_ID,
        name: "Alex salary",
        income_type: "salary",
        amount: 6800,
        frequency: "monthly",
        visibility: "shared",
        is_active: true,
        notes: null,
        created_at: isoDaysAgo(80),
        updated_at: isoDaysAgo(1),
      },
      {
        id: "income-jamie",
        workspace_id: WORKSPACE_ID,
        owner_id: JAMIE_ID,
        name: "Jamie salary",
        income_type: "salary",
        amount: 5900,
        frequency: "monthly",
        visibility: "shared",
        is_active: true,
        notes: null,
        created_at: isoDaysAgo(80),
        updated_at: isoDaysAgo(1),
      },
      {
        id: "income-side",
        workspace_id: WORKSPACE_ID,
        owner_id: ALEX_ID,
        name: "Freelance projects",
        income_type: "freelance",
        amount: 900,
        frequency: "irregular",
        visibility: "private",
        is_active: true,
        notes: null,
        created_at: isoDaysAgo(45),
        updated_at: isoDaysAgo(5),
      },
    ],
    expenses: [
      {
        id: "expense-rent",
        workspace_id: WORKSPACE_ID,
        created_by: ALEX_ID,
        paid_by: ALEX_ID,
        description: "Rent",
        amount: 2800,
        category: "housing",
        expense_date: currentMonthDate(1),
        expense_type: "shared",
        visibility: "household",
        is_recurring: true,
        recurrence: "monthly",
        split_method: "income_based",
        is_settled: true,
        settled_at: isoDaysAgo(2),
        merchant: "Oak Street Flats",
        notes: null,
        created_at: isoDaysAgo(12),
        updated_at: isoDaysAgo(2),
      },
      {
        id: "expense-groceries",
        workspace_id: WORKSPACE_ID,
        created_by: JAMIE_ID,
        paid_by: JAMIE_ID,
        description: "Groceries",
        amount: 186.42,
        category: "groceries",
        expense_date: daysAgo(3),
        expense_type: "shared",
        visibility: "shared",
        is_recurring: false,
        recurrence: null,
        split_method: "equal",
        is_settled: false,
        settled_at: null,
        merchant: "Market Basket",
        notes: null,
        created_at: isoDaysAgo(3),
        updated_at: isoDaysAgo(3),
      },
      {
        id: "expense-utilities",
        workspace_id: WORKSPACE_ID,
        created_by: ALEX_ID,
        paid_by: ALEX_ID,
        description: "Utilities",
        amount: 240,
        category: "utilities",
        expense_date: currentMonthDate(6),
        expense_type: "shared",
        visibility: "household",
        is_recurring: true,
        recurrence: "monthly",
        split_method: "income_based",
        is_settled: true,
        settled_at: isoDaysAgo(1),
        merchant: "City Power",
        notes: null,
        created_at: isoDaysAgo(7),
        updated_at: isoDaysAgo(1),
      },
      {
        id: "expense-dining",
        workspace_id: WORKSPACE_ID,
        created_by: ALEX_ID,
        paid_by: ALEX_ID,
        description: "Dinner out",
        amount: 94.3,
        category: "dining",
        expense_date: daysAgo(5),
        expense_type: "shared",
        visibility: "shared",
        is_recurring: false,
        recurrence: null,
        split_method: "equal",
        is_settled: false,
        settled_at: null,
        merchant: "Little Garden",
        notes: null,
        created_at: isoDaysAgo(5),
        updated_at: isoDaysAgo(5),
      },
      {
        id: "expense-prior-grocery",
        workspace_id: WORKSPACE_ID,
        created_by: JAMIE_ID,
        paid_by: JAMIE_ID,
        description: "Groceries",
        amount: 720,
        category: "groceries",
        expense_date: previousMonthDate(18),
        expense_type: "shared",
        visibility: "shared",
        is_recurring: false,
        recurrence: null,
        split_method: "equal",
        is_settled: true,
        settled_at: isoDaysAgo(15),
        merchant: null,
        notes: null,
        created_at: isoDaysAgo(25),
        updated_at: isoDaysAgo(15),
      },
    ],
    billPayments: [
      {
        id: "bill-payment-rent-current",
        workspace_id: WORKSPACE_ID,
        expense_id: "expense-rent",
        month: monthStart(new Date()),
        paid_on: currentMonthDate(1),
        amount: 2800,
        note: "Paid from joint checking",
        created_by: ALEX_ID,
        created_at: isoDaysAgo(4),
        updated_at: isoDaysAgo(4),
      },
    ],
    budgets: [
      {
        id: "budget-housing",
        workspace_id: WORKSPACE_ID,
        owner_id: null,
        category: "housing",
        amount: 3000,
        month: currentMonth,
        scope: "household",
        visibility: "household",
        rollover: false,
        created_at: isoDaysAgo(20),
        updated_at: isoDaysAgo(1),
      },
      {
        id: "budget-groceries",
        workspace_id: WORKSPACE_ID,
        owner_id: null,
        category: "groceries",
        amount: 850,
        month: currentMonth,
        scope: "household",
        visibility: "shared",
        rollover: false,
        created_at: isoDaysAgo(20),
        updated_at: isoDaysAgo(1),
      },
      {
        id: "budget-dining",
        workspace_id: WORKSPACE_ID,
        owner_id: null,
        category: "dining",
        amount: 420,
        month: currentMonth,
        scope: "household",
        visibility: "shared",
        rollover: false,
        created_at: isoDaysAgo(20),
        updated_at: isoDaysAgo(1),
      },
    ],
    goals: [
      {
        id: "goal-emergency",
        workspace_id: WORKSPACE_ID,
        created_by: ALEX_ID,
        name: "Six month emergency fund",
        goal_type: "emergency_fund",
        target_amount: 30000,
        target_date: dateOnly(nextYear),
        monthly_contribution: 900,
        visibility: "household",
        status: "active",
        emoji: "🛟",
        notes: "Cover essentials before larger investments.",
        created_at: isoDaysAgo(75),
        updated_at: isoDaysAgo(1),
        goal_contributions: [
          {
            id: "contrib-emergency-1",
            goal_id: "goal-emergency",
            user_id: ALEX_ID,
            amount: 9000,
            contributed_on: previousMonthDate(10),
            note: null,
            created_at: isoDaysAgo(30),
          },
          {
            id: "contrib-emergency-2",
            goal_id: "goal-emergency",
            user_id: JAMIE_ID,
            amount: 5850,
            contributed_on: currentMonthDate(8),
            note: null,
            created_at: isoDaysAgo(5),
          },
        ],
      },
      {
        id: "goal-travel",
        workspace_id: WORKSPACE_ID,
        created_by: JAMIE_ID,
        name: "Japan anniversary trip",
        goal_type: "travel",
        target_amount: 8000,
        target_date: dateOnly(nextQuarter),
        monthly_contribution: 750,
        visibility: "shared",
        status: "active",
        emoji: "✈️",
        notes: null,
        created_at: isoDaysAgo(60),
        updated_at: isoDaysAgo(4),
        goal_contributions: [
          {
            id: "contrib-travel-1",
            goal_id: "goal-travel",
            user_id: ALEX_ID,
            amount: 2100,
            contributed_on: previousMonthDate(20),
            note: null,
            created_at: isoDaysAgo(20),
          },
          {
            id: "contrib-travel-2",
            goal_id: "goal-travel",
            user_id: JAMIE_ID,
            amount: 1900,
            contributed_on: daysAgo(2),
            note: null,
            created_at: isoDaysAgo(2),
          },
        ],
      },
    ],
    investments: [
      {
        id: "investment-index",
        workspace_id: WORKSPACE_ID,
        owner_id: ALEX_ID,
        name: "Brokerage index fund",
        asset_class: "etf",
        account_name: "Demo Invest",
        risk_level: "medium",
        visibility: "shared",
        is_watchlist: false,
        research_notes: null,
        notes: null,
        created_at: isoDaysAgo(70),
        updated_at: isoDaysAgo(1),
        investment_holdings: [
          {
            id: "holding-vti",
            investment_id: "investment-index",
            symbol: "VTI",
            name: "Total market ETF",
            quantity: 42,
            cost_basis: 9200,
            current_value: 10850,
            as_of: daysAgo(1),
            notes: null,
            created_at: isoDaysAgo(70),
            updated_at: isoDaysAgo(1),
          },
        ],
      },
      {
        id: "investment-401k",
        workspace_id: WORKSPACE_ID,
        owner_id: JAMIE_ID,
        name: "Jamie retirement",
        asset_class: "retirement",
        account_name: "Work 401k",
        risk_level: "medium",
        visibility: "shared",
        is_watchlist: false,
        research_notes: null,
        notes: null,
        created_at: isoDaysAgo(70),
        updated_at: isoDaysAgo(1),
        investment_holdings: [
          {
            id: "holding-target",
            investment_id: "investment-401k",
            symbol: null,
            name: "Target date fund",
            quantity: null,
            cost_basis: 18500,
            current_value: 20200,
            as_of: daysAgo(1),
            notes: null,
            created_at: isoDaysAgo(70),
            updated_at: isoDaysAgo(1),
          },
        ],
      },
    ],
    debts: [
      {
        id: "debt-card",
        workspace_id: WORKSPACE_ID,
        owner_id: ALEX_ID,
        name: "Travel card",
        debt_type: "credit_card",
        balance: 2200,
        original_balance: 4200,
        apr: 19.99,
        minimum_payment: 85,
        due_day: 18,
        visibility: "shared",
        status: "active",
        notes: null,
        created_at: isoDaysAgo(70),
        updated_at: isoDaysAgo(2),
      },
      {
        id: "debt-car",
        workspace_id: WORKSPACE_ID,
        owner_id: JAMIE_ID,
        name: "Car loan",
        debt_type: "car_loan",
        balance: 9100,
        original_balance: 18000,
        apr: 5.9,
        minimum_payment: 360,
        due_day: 22,
        visibility: "shared",
        status: "active",
        notes: null,
        created_at: isoDaysAgo(70),
        updated_at: isoDaysAgo(2),
      },
    ],
    researchItems: [
      {
        id: "research-rent-buy",
        workspace_id: WORKSPACE_ID,
        created_by: ALEX_ID,
        title: "Renew lease or start house hunting?",
        decision_type: "rent_vs_buy",
        notes: "Compare down payment pace with likely rent increase.",
        pros: ["More stability", "Build equity"],
        cons: ["Higher upfront cost", "Less flexibility"],
        estimated_cost: 65000,
        final_decision: null,
        status: "discussing",
        visibility: "shared",
        decided_at: null,
        created_at: isoDaysAgo(18),
        updated_at: isoDaysAgo(3),
      },
    ],
    checkins: [
      {
        id: "checkin-current",
        workspace_id: WORKSPACE_ID,
        month: currentMonth,
        title: "July money check-in",
        status: "answering",
        scheduled_for: currentMonthDate(15),
        summary: null,
        action_items: [
          { id: "action-1", text: "Review grocery budget", assigned_to: ALEX_ID, done: false },
        ],
        created_by: ALEX_ID,
        completed_at: null,
        created_at: isoDaysAgo(6),
        updated_at: isoDaysAgo(2),
      },
    ],
    documents: [
      {
        id: "doc-policy",
        workspace_id: WORKSPACE_ID,
        owner_id: JAMIE_ID,
        name: "Renters insurance policy",
        category: "insurance",
        storage_path: "demo/renters-policy.pdf",
        file_size: 420000,
        mime_type: "application/pdf",
        visibility: "household",
        expires_on: dateOnly(nextYear),
        reminder_on: dateOnly(nextQuarter),
        notes: "Renew before lease anniversary.",
        created_at: isoDaysAgo(35),
        updated_at: isoDaysAgo(5),
      },
    ],
    tasks: [
      {
        id: "task-groceries",
        workspace_id: WORKSPACE_ID,
        created_by: JAMIE_ID,
        assigned_to: ALEX_ID,
        title: "Update grocery budget after Costco run",
        description: null,
        due_on: daysAgo(-2),
        status: "open",
        priority: "medium",
        related_type: "expense",
        related_id: "expense-groceries",
        completed_at: null,
        created_at: isoDaysAgo(2),
        updated_at: isoDaysAgo(2),
      },
      {
        id: "task-card",
        workspace_id: WORKSPACE_ID,
        created_by: ALEX_ID,
        assigned_to: ALEX_ID,
        title: "Pay extra toward travel card",
        description: "Use the leftover dining budget.",
        due_on: currentMonthDate(20),
        status: "in_progress",
        priority: "high",
        related_type: "debt",
        related_id: "debt-card",
        completed_at: null,
        created_at: isoDaysAgo(4),
        updated_at: isoDaysAgo(1),
      },
    ],
    events: [
      {
        id: "event-checkin",
        workspace_id: WORKSPACE_ID,
        actor_id: ALEX_ID,
        event_type: "checkin.started",
        entity_type: "checkin",
        entity_id: "checkin-current",
        summary: "Alex started the July money check-in",
        metadata: {},
        visibility: "household",
        created_at: isoDaysAgo(6),
      },
      {
        id: "event-grocery",
        workspace_id: WORKSPACE_ID,
        actor_id: JAMIE_ID,
        event_type: "expense.created",
        entity_type: "expense",
        entity_id: "expense-groceries",
        summary: "Jamie added groceries for $186.42",
        metadata: {},
        visibility: "shared",
        created_at: isoDaysAgo(3),
      },
    ],
    approvals: [],
  };
}
